const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
const app = {list: [], totals: {}, selectedID: sessionStorage.getItem('selectedDossier') || '', detail: null, matrix: null, issues: [], permits: [], auditPage: 1, auditTotal: 0};

function escapeHTML(value) { return String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function local(value) { return value ? new Date(value).toLocaleString('zh-CN', {hour12:false}) : '—'; }
function inputTime(value) { if (!value) return ''; const d = new Date(value); return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16); }
function notice(message, error=false) { const box=$('#notice'); box.textContent=message; box.style.background=error?'#9d332a':'#173d49'; box.style.display='block'; clearTimeout(notice.timer); notice.timer=setTimeout(()=>box.style.display='none',5000); }
async function api(path, options={}) { const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}}); let data={}; try{data=await response.json()}catch{} if(!response.ok){const error=new Error(data.error||`请求失败（${response.status}）`);error.data=data;error.status=response.status;throw error} return data; }
function expected() { return app.detail?.version || 0; }

function filterQuery() { const f=new FormData($('#filters')); const q=new URLSearchParams(); for(const key of ['status','venue','keyword']) if(f.get(key))q.set(key,f.get(key)); for(const key of ['from','to']) if(f.get(key))q.set(key,new Date(f.get(key)).toISOString()); if(f.get('unissued'))q.set('unissued','true'); return q.toString(); }
async function loadList() { const data=await api('/api/dossiers?'+filterQuery()); app.list=data.dossiers||[];app.totals=data.totals||{};renderTotals();renderList();if(app.selectedID&&!app.list.some(x=>x.dossier.id===app.selectedID)){app.selectedID='';sessionStorage.removeItem('selectedDossier')}if(app.selectedID)await loadDetail();else showEmpty();$('#connection').textContent=`已加载 ${app.list.length} 个档案`; }
async function loadDetail() { if(!app.selectedID)return; const id=encodeURIComponent(app.selectedID); const [d, inspections, issues, permits]=await Promise.all([api(`/api/dossiers/${id}`),api(`/api/dossiers/${id}/inspections`),api(`/api/dossiers/${id}/issues`),api(`/api/dossiers/${id}/permit`)]);app.detail=d;app.matrix=inspections.matrix;app.issues=issues.issues||[];app.permits=permits.permits||[];renderDetail();await loadAudit(); }
function showEmpty(){app.detail=null;$('#empty').hidden=false;$('#detail').hidden=true;}
function renderTotals(){const t=app.totals;const statuses=Object.entries(t.byStatus||{}).map(([k,v])=>`${escapeHTML(k)} ${v}`).join(' · ')||'暂无';$('#totals').innerHTML=`<button class="metric" data-summary="all"><b>${t.total||0}</b>筛选结果<br><span class="small">${statuses}</span></button><button class="metric" data-summary="unissued"><b>${t.next24HoursUnissued||0}</b>未来24小时未签发</button><div class="metric"><b>${t.criticalIssues||0}</b>未解决严重问题</div><div class="metric"><b>${app.list.filter(x=>x.pendingReview>0).length}</b>存在待复核档案</div>`;}
function renderList(){if(!app.list.length){$('#dossiers').innerHTML='<p class="empty">没有符合筛选条件的档案。</p>';return}$('#dossiers').innerHTML=app.list.map(x=>{const d=x.dossier;return `<button class="list-item ${d.id===app.selectedID?'active':''}" data-dossier="${escapeHTML(d.id)}"><b>${escapeHTML(d.showName)}</b><br><span class="tag">${escapeHTML(d.status)} · v${d.version}</span><br><span class="small">${escapeHTML(d.venue)} · ${local(d.scheduledAt)}<br>检查 ${Math.round(x.inspectionRatio*100)}% · 待复核 ${x.pendingReview} · ${x.permitStatus}</span></button>`}).join('');}
function renderDetail(){const d=app.detail;$('#empty').hidden=true;$('#detail').hidden=false;$('#dossier-title').textContent=d.showName;$('#dossier-meta').innerHTML=`<span class="tag">${escapeHTML(d.status)} · v${d.version}</span><p>${escapeHTML(d.venue)} · ${local(d.scheduledAt)} · 更新于 ${local(d.updatedAt)}</p><p class="small">${d.equipmentBoundary.map(e=>`${escapeHTML(e.id)} ${escapeHTML(e.name)} / ${e.ratedLoadKg}kg / ${escapeHTML(e.isolationBoundary)}`).join('<br>')}</p>`;$('#edit-dossier').hidden=d.status!=='草稿';renderMatrix();renderIssues();renderPermit();$('#freeze').hidden=d.status!=='待复核';$('#issue-permit').hidden=d.status!=='已冻结';}
function renderMatrix(){const m=app.matrix;if(!m)return;$('#matrix-summary').innerHTML=`<p>应检 <b>${m.required}</b> · 已检 <b>${m.completed}</b> · 通过 ${m.passed} · 不通过 ${m.failed} · 缺失 <b>${m.missing}</b></p><div class="progress"><i style="width:${m.completionRatio*100}%"></i></div>`;const byEquipment=Object.groupBy?Object.groupBy(m.cells,x=>x.equipmentID):m.cells.reduce((a,x)=>((a[x.equipmentID]??=[]).push(x),a),{});$('#matrix').innerHTML=`<table><thead><tr><th>设备</th>${[...new Map(m.cells.map(x=>[x.check.code,x.check])).values()].map(x=>`<th>${escapeHTML(x.name)}</th>`).join('')}</tr></thead><tbody>${Object.entries(byEquipment).map(([equipment,cells])=>`<tr><th>${escapeHTML(equipment)}</th>${cells.map(c=>`<td class="cell ${c.missing?'missing':c.inspection?.result==='不通过'?'failed':''}" data-equipment="${escapeHTML(equipment)}" data-check="${escapeHTML(c.check.code)}">${c.missing?'缺失':`${escapeHTML(c.inspection.result)}<br><span class="small">${escapeHTML(c.inspection.inspector)}<br>${local(c.inspection.recordedAt)}</span>`}</td>`).join('')}</tr>`).join('')}</tbody></table>`;}
function renderIssues(){if(!app.issues.length){$('#issues').innerHTML='<p class="ok">当前没有风险问题。</p>';return}app.issues.sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt));$('#issues').innerHTML=app.issues.map(x=>{const state=x.pendingElimination?'待安全员确认消除':x.reviewDecision;const type=x.checkCode;const retest=type==='LOAD_LIMIT'?'<input type="number" step="0.01" data-field="measuredLoadKg" placeholder="结构化复测载荷 kg">':type==='LIMIT_RESPONSE'?'<input type="number" data-field="limitResponseMs" placeholder="结构化复测响应 ms">':'<select data-field="emergencyStopResult"><option value="">不带入复测</option><option>通过</option><option>失败</option></select>';return `<div class="issue ${x.severity==='严重'?'critical':''} ${x.reviewDecision==='通过'?'passed':''}" data-issue="${escapeHTML(x.id)}"><div class="title-row"><b>${escapeHTML(x.severity)} · ${escapeHTML(x.equipmentID)} · ${escapeHTML(x.ruleCode)}</b><span class="tag">${escapeHTML(state)}</span></div><p>${escapeHTML(x.description)}</p><p class="small">整改修订 v${x.revision} · 重开 ${x.reopenCount} 次 · 最近检测 ${local(x.lastDetectedAt)}</p><div class="retest">${retest}</div><div class="issue-actions"><button data-action="remediate">提交整改修订</button><button data-action="review-pass">逐项通过</button><button class="danger" data-action="review-return">退回</button>${x.revision?`<button class="secondary" data-action="revision" data-revision="${x.revision}">查看修订对比</button>`:''}</div></div>`}).join('');}
function renderPermit(){const p=app.permits[0];$('#permit-current').innerHTML=p?`<p class="ok">已签发：<b>${escapeHTML(p.permitCode)}</b> · 冻结版本 v${p.frozenVersion}</p><code>${escapeHTML(p.contentHash)}</code>`:'<p class="small">尚未签发启用许可。</p>';if(p)$('#verify-form [name=code]').value=p.permitCode;}

function equipmentRows(items){return items.map((e,i)=>`<div class="equipment-row" data-row="${i}"><input name="equipmentID" value="${escapeHTML(e.id)}" placeholder="设备编号" required><input name="equipmentName" value="${escapeHTML(e.name)}" placeholder="设备名称" required><input name="ratedLoadKg" type="number" step="0.01" value="${e.ratedLoadKg}" placeholder="额定载荷" required><input name="boundary" value="${escapeHTML(e.isolationBoundary)}" placeholder="隔离边界" required><button type="button" class="danger remove-row">移除</button></div>`).join('');}
function openDossierForm(d){const form=$('#dossier-form');form.dataset.mode=d?'edit':'create';const values=d||{showName:'',venue:'',scheduledAt:new Date(Date.now()+86400000).toISOString(),equipmentBoundary:[{id:'',name:'',ratedLoadKg:1000,isolationBoundary:''}]};form.innerHTML=`<h3>${d?'修订草稿档案':'新建档案'}</h3><div class="form-grid"><label>演出名称<input name="showName" value="${escapeHTML(values.showName)}" required></label><label>场地<input name="venue" value="${escapeHTML(values.venue)}" required></label><label>演出时间<input name="scheduledAt" type="datetime-local" value="${inputTime(values.scheduledAt)}" required></label><label>${d?'操作者':'创建人'}<input name="actor" value="${escapeHTML(d?.createdBy||'工程师')}" required></label></div><h4>设备边界</h4><div id="equipment-rows">${equipmentRows(values.equipmentBoundary)}</div><button type="button" id="add-equipment">添加设备</button><button>提交</button><button type="button" class="secondary close-form">取消</button>`;form.hidden=false;}
function inspectionInput(cell){const old=cell.inspection||{};const form=$('#inspection-form');form.dataset.equipment=cell.equipmentID;form.dataset.check=cell.check.code;form.innerHTML=`<h3>${old.id?'更正':'录入'} ${escapeHTML(cell.equipmentID)} / ${escapeHTML(cell.check.name)}</h3><div class="form-grid"><label>结果<select name="result"><option>通过</option><option ${old.result==='不通过'?'selected':''}>不通过</option></select></label><label>检查人<input name="inspector" value="${escapeHTML(old.inspector||'工程师')}" required></label>${cell.check.code==='LOAD_LIMIT'?`<label>实测载荷 kg<input name="measuredLoadKg" type="number" step="0.01" value="${old.measuredLoadKg||''}" required></label>`:''}${cell.check.code==='LIMIT_RESPONSE'?`<label>响应毫秒<input name="limitResponseMs" type="number" value="${old.limitResponseMs||''}" required></label>`:''}${cell.check.code==='EMERGENCY_STOP'?`<label>急停动作<select name="emergencyStopResult"><option>通过</option><option ${old.emergencyStopResult==='失败'?'selected':''}>失败</option></select></label>`:''}<label class="wide">现场备注<textarea name="notes">${escapeHTML(old.notes||'')}</textarea></label></div><button>保存</button><button type="button" class="secondary close-form">取消</button>`;form.hidden=false;}
function openBatch(){const missing=app.matrix.missingItems;if(!missing.length){notice('当前没有缺失检查项');return}const form=$('#batch-form');form.innerHTML=`<h3>批量录入缺失项</h3><label>统一检查人<input name="actor" value="工程师" required></label><table class="batch-table"><thead><tr><th>设备/项目</th><th>结果</th><th>专属测量值</th><th>备注</th></tr></thead><tbody>${missing.map((c,i)=>`<tr data-index="${i}" data-equipment="${escapeHTML(c.equipmentID)}" data-check="${escapeHTML(c.check.code)}"><td>${escapeHTML(c.equipmentID)}<br>${escapeHTML(c.check.name)}</td><td><select name="result"><option>通过</option><option>不通过</option></select></td><td>${c.check.code==='LOAD_LIMIT'?'<input name="value" type="number" step="0.01" required placeholder="kg">':c.check.code==='LIMIT_RESPONSE'?'<input name="value" type="number" required placeholder="ms">':'<select name="value"><option>通过</option><option>失败</option></select>'}</td><td><input name="notes"></td></tr>`).join('')}</tbody></table><button>原子提交 ${missing.length} 项</button><button type="button" class="secondary close-form">取消</button>`;form.hidden=false;}
function openRemediation(issue){const form=$('#remediation-form');form.dataset.issue=issue.id;const now=inputTime(new Date().toISOString());form.innerHTML=`<h3>${escapeHTML(issue.id)} 整改修订</h3><p class="small">${issue.severity==='高级'||issue.severity==='严重'?'必须同时提交现场照片与复测记录。':'请提交可核验证据。'}</p><label>整改说明<textarea name="remediation" required>${escapeHTML(issue.remediation||'')}</textarea></label><label>复测数据<textarea name="retestData" required>${escapeHTML(issue.retestData||'')}</textarea></label><div class="evidence-row"><input value="现场照片" data-name><select data-type><option>现场照片</option><option>现场视频</option><option>文档</option><option>复测记录</option></select><input type="datetime-local" value="${now}" data-at><input placeholder="引用地址" data-ref required><input placeholder="内容摘要" data-digest required></div><div class="evidence-row"><input value="复测记录" data-name><select data-type><option>复测记录</option><option>现场照片</option><option>文档</option><option>现场视频</option></select><input type="datetime-local" value="${now}" data-at><input placeholder="引用地址" data-ref required><input placeholder="内容摘要" data-digest required></div><button>提交新修订</button><button type="button" class="secondary close-form">取消</button>`;form.hidden=false;form.scrollIntoView({behavior:'smooth'});}

$('#filters').addEventListener('submit',e=>{e.preventDefault();loadList().catch(handle)});
$('#totals').addEventListener('click',e=>{const key=e.target.closest('[data-summary]')?.dataset.summary;if(!key)return;if(key==='unissued'){const now=new Date();$('#filters [name=unissued]').checked=true;$('#filters [name=from]').value=inputTime(now);$('#filters [name=to]').value=inputTime(new Date(now.getTime()+86400000))}else $('#filters').reset();loadList().catch(handle)});
$('#dossiers').addEventListener('click',e=>{const row=e.target.closest('[data-dossier]');if(!row)return;app.selectedID=row.dataset.dossier;sessionStorage.setItem('selectedDossier',app.selectedID);renderList();loadDetail().catch(handle)});
$('#create').onclick=()=>openDossierForm(null);$('#edit-dossier').onclick=()=>openDossierForm(app.detail);
$('#dossier-form').addEventListener('click',e=>{if(e.target.id==='add-equipment')$('#equipment-rows').insertAdjacentHTML('beforeend',equipmentRows([{id:'',name:'',ratedLoadKg:1000,isolationBoundary:''}]));if(e.target.classList.contains('remove-row'))e.target.closest('.equipment-row').remove();if(e.target.classList.contains('close-form'))e.currentTarget.hidden=true;});
$('#dossier-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;const equipmentBoundary=$$('.equipment-row',form).map(row=>({id:$('[name=equipmentID]',row).value,name:$('[name=equipmentName]',row).value,ratedLoadKg:Number($('[name=ratedLoadKg]',row).value),isolationBoundary:$('[name=boundary]',row).value}));const body={showName:form.showName.value,venue:form.venue.value,scheduledAt:new Date(form.scheduledAt.value).toISOString(),equipmentBoundary};if(form.dataset.mode==='create'){body.createdBy=form.actor.value;const d=await api('/api/dossiers',{method:'POST',body:JSON.stringify(body),headers:{'Idempotency-Key':crypto.randomUUID()}});app.selectedID=d.id;sessionStorage.setItem('selectedDossier',d.id)}else{body.actor=form.actor.value;body.expectedVersion=expected();await api(`/api/dossiers/${encodeURIComponent(app.selectedID)}`,{method:'PATCH',body:JSON.stringify(body)})}form.hidden=true;await loadList();notice('档案已保存');});
$('#matrix').addEventListener('click',e=>{const td=e.target.closest('[data-equipment]');if(!td)return;const cell=app.matrix.cells.find(x=>x.equipmentID===td.dataset.equipment&&x.check.code===td.dataset.check);inspectionInput(cell)});$('#add-batch').onclick=openBatch;
$('#inspection-form').addEventListener('click',e=>{if(e.target.classList.contains('close-form'))e.currentTarget.hidden=true});$('#inspection-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;const body={equipmentID:f.dataset.equipment,checkCode:f.dataset.check,result:f.result.value,inspector:f.inspector.value,notes:f.notes.value,expectedVersion:expected()};if(f.measuredLoadKg)body.measuredLoadKg=Number(f.measuredLoadKg.value);if(f.limitResponseMs)body.limitResponseMs=Number(f.limitResponseMs.value);if(f.emergencyStopResult)body.emergencyStopResult=f.emergencyStopResult.value;await api(`/api/dossiers/${encodeURIComponent(app.selectedID)}/inspections`,{method:'POST',body:JSON.stringify(body)});f.hidden=true;await loadList();notice('检查结果已保存，重复业务键已作为更正处理');});
$('#batch-form').addEventListener('click',e=>{if(e.target.classList.contains('close-form'))e.currentTarget.hidden=true});$('#batch-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;const actor=f.actor.value;const items=$$('tbody tr',f).map(row=>{const code=row.dataset.check;const value=$('[name=value]',row).value;return{equipmentID:row.dataset.equipment,checkCode:code,result:$('[name=result]',row).value,inspector:actor,notes:$('[name=notes]',row).value,measuredLoadKg:code==='LOAD_LIMIT'?Number(value):0,limitResponseMs:code==='LIMIT_RESPONSE'?Number(value):0,emergencyStopResult:code==='EMERGENCY_STOP'?value:''}});const result=await api(`/api/dossiers/${encodeURIComponent(app.selectedID)}/inspections`,{method:'POST',body:JSON.stringify({actor,expectedVersion:expected(),items}),headers:{'Idempotency-Key':crypto.randomUUID()}});f.hidden=true;await loadList();notice(`批量提交成功：新增 ${result.added}，更正 ${result.corrected}`);});
$('#detect').onclick=async()=>{const retestValues=[];$$('.issue').forEach(card=>{const field=$('[data-field]',card);if(!field||!field.value)return;const item={issueID:card.dataset.issue};if(field.dataset.field==='measuredLoadKg')item.measuredLoadKg=Number(field.value);if(field.dataset.field==='limitResponseMs')item.limitResponseMs=Number(field.value);if(field.dataset.field==='emergencyStopResult')item.emergencyStopResult=field.value;retestValues.push(item)});try{const r=await api(`/api/dossiers/${encodeURIComponent(app.selectedID)}/issues/check`,{method:'POST',body:JSON.stringify({actor:'工程师',expectedVersion:expected(),retestValues})});$('#detect-result').innerHTML=`<p class="ok">风险对账完成：新增 ${r.new}、持续 ${r.continuing}、待确认消除 ${r.pendingElimination}、重开 ${r.reopened}</p>`;await loadList()}catch(error){if(error.data?.missingItems){$('#detect-result').innerHTML=`<p class="warn">${escapeHTML(error.message)}：${error.data.missingItems.map(x=>`${escapeHTML(x.equipmentID)}/${escapeHTML(x.check.code)}`).join('、')}</p>`;const first=error.data.missingItems[0];$(`[data-equipment="${CSS.escape(first.equipmentID)}"][data-check="${CSS.escape(first.check.code)}"]`)?.scrollIntoView({behavior:'smooth'})}else handle(error)}};
$('#issues').addEventListener('click',async e=>{const button=e.target.closest('[data-action]');if(!button)return;const issue=app.issues.find(x=>x.id===button.closest('.issue').dataset.issue);if(button.dataset.action==='remediate'){openRemediation(issue);return}if(button.dataset.action==='revision'){const data=await api(`/api/issues/${encodeURIComponent(issue.id)}/revisions/${button.dataset.revision}`);$('#revision-detail').innerHTML=`<div class="drawer"><b>整改修订 v${data.revision.revision}</b><p>提交：${escapeHTML(data.revision.submittedBy)} · ${local(data.revision.submittedAt)}</p><p>${escapeHTML(data.revision.remediation)} / ${escapeHTML(data.revision.retestData)}</p>${data.diff?`<p class="small">相邻对比：复测 ${escapeHTML(data.diff.retestBefore)} → ${escapeHTML(data.diff.retestAfter)}；新增证据 ${escapeHTML(data.diff.addedEvidence.join('、')||'无')}；移除证据 ${escapeHTML(data.diff.removedEvidence.join('、')||'无')}</p>`:''}</div>`;return}const decision=button.dataset.action==='review-pass'?'通过':'退回';const note=decision==='退回'?prompt('请输入退回原因','证据或复测数据需补充'):prompt('复核意见','整改与证据核验通过');if(note===null)return;await api(`/api/issues/${encodeURIComponent(issue.id)}/review`,{method:'POST',body:JSON.stringify({actor:'安全员',decision,note,expectedVersion:expected()})});await loadList();notice(`问题已${decision}`);});
$('#remediation-form').addEventListener('click',e=>{if(e.target.classList.contains('close-form'))e.currentTarget.hidden=true});$('#remediation-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;const evidence=$$('.evidence-row',f).map(row=>({name:$('[data-name]',row).value,type:$('[data-type]',row).value,collectedAt:new Date($('[data-at]',row).value).toISOString(),reference:$('[data-ref]',row).value,digest:$('[data-digest]',row).value}));await api(`/api/issues/${encodeURIComponent(f.dataset.issue)}/remediation`,{method:'POST',body:JSON.stringify({actor:'工程师',remediation:f.remediation.value,retestData:f.retestData.value,evidence,expectedVersion:expected()})});f.hidden=true;await loadList();notice('整改修订及证据快照已保存');});
$('#freeze').onclick=async()=>{try{await api(`/api/dossiers/${encodeURIComponent(app.selectedID)}/freeze`,{method:'POST',body:JSON.stringify({actor:'安全员',expectedVersion:expected()})});await loadList();notice('候选安全版本已冻结')}catch(error){if(error.data?.blockingIssues)notice(error.data.blockingIssues.map(x=>`${x.issueID}: ${x.reason}`).join('；'),true);else handle(error)}};
$('#issue-permit').onclick=async()=>{const p=await api(`/api/dossiers/${encodeURIComponent(app.selectedID)}/permit`,{method:'POST',body:JSON.stringify({actor:'值班经理',expectedVersion:expected()}),headers:{'Idempotency-Key':crypto.randomUUID()}});await loadList();$('#verify-form [name=code]').value=p.permitCode;notice('启用许可已签发');};
$('#verify-form').addEventListener('submit',async e=>{e.preventDefault();const code=e.currentTarget.code.value.trim();try{const result=await api(`/api/permits/${encodeURIComponent(code)}/verify`);$('#verify-result').innerHTML=`<div class="${result.valid?'ok':'error'}"><b>${escapeHTML(result.message)}</b>（${escapeHTML(result.reasonCode)}）<p>${escapeHTML(result.dossier.showName||'')} · 冻结版本 v${result.permit.frozenVersion} · 签发人 ${escapeHTML(result.permit.issuedBy)} · ${local(result.permit.issuedAt)}</p><code>${escapeHTML(result.recalculatedHash||result.permit.contentHash)}</code></div>`}catch(error){$('#verify-result').innerHTML=`<p class="error">${escapeHTML(error.message)}</p>`}});
async function loadAudit(){if(!app.selectedID)return;const type=$('#audit-type').value;const data=await api(`/api/dossiers/${encodeURIComponent(app.selectedID)}/audit?page=${app.auditPage}&pageSize=10&type=${encodeURIComponent(type)}`);app.auditTotal=data.total;$('#timeline').innerHTML=data.events.length?data.events.map(x=>`<div class="audit"><b>${escapeHTML(x.type)}</b> · ${escapeHTML(x.actor)} · ${local(x.at)}<br><span class="small">v${x.version} · ${escapeHTML(x.detail)}</span></div>`).join(''):'<p class="empty">当前筛选没有审计事件。</p>';$('#audit-page').textContent=`第 ${app.auditPage} 页 / 共 ${data.total} 条`;$('#audit-prev').disabled=app.auditPage===1;$('#audit-next').disabled=app.auditPage*10>=data.total;}
$('#audit-type').onchange=()=>{app.auditPage=1;loadAudit().catch(handle)};$('#audit-prev').onclick=()=>{if(app.auditPage>1){app.auditPage--;loadAudit().catch(handle)}};$('#audit-next').onclick=()=>{if(app.auditPage*10<app.auditTotal){app.auditPage++;loadAudit().catch(handle)}};
function handle(error){console.error(error);notice(error.status===409?`${error.message}。已保留输入，请刷新最新版本后重试。`:error.message,true)}
window.addEventListener('unhandledrejection',event=>{event.preventDefault();handle(event.reason)});
loadList().catch(handle);
